
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: Life School Riviera
subtitle: "Vivre l'Ã©cole autrement"
url: "https://lifeschool-riviera.ch/" # the base hostname & protocol for your site
# baseurl: "/the/subpath/of/your/site" # Set this value to "" if you want your site to be root
baseurl: ""
cover: "/img/slider-bg.jpg"
logo: "/img/logo.png"
future: true  # consider all posts (_posts folder), not only items with a date in the past

# Build settings
markdown: kramdown

# Google analytics
ga_tracking_id: "GTM-5ZG44CP"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."


defaults:
  -
    scope:
      type: redirects
    values:
      layout: redirect
